FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && apt-get install -y --no-install-recommends \
    flex \
    bison \
    gcc \
    g++ \
    make \
    && rm -rf /var/lib/apt/lists/*
